// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ArgonneDashboard.ArgonneServiceClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class AdAggregateData
    {
        /// <summary>
        /// Initializes a new instance of the AdAggregateData class.
        /// </summary>
        public AdAggregateData() { }

        /// <summary>
        /// Initializes a new instance of the AdAggregateData class.
        /// </summary>
        public AdAggregateData(Guid? adId = default(Guid?), int? totalFaces = default(int?), int? uniqueFaces = default(int?), int? males = default(int?), int? females = default(int?), int? ageBracket1 = default(int?), int? ageBracket2 = default(int?), int? ageBracket3 = default(int?), int? ageBracket4 = default(int?), int? ageBracket5 = default(int?), int? ageBracket6 = default(int?))
        {
            AdId = adId;
            TotalFaces = totalFaces;
            UniqueFaces = uniqueFaces;
            Males = males;
            Females = females;
            AgeBracket1 = ageBracket1;
            AgeBracket2 = ageBracket2;
            AgeBracket3 = ageBracket3;
            AgeBracket4 = ageBracket4;
            AgeBracket5 = ageBracket5;
            AgeBracket6 = ageBracket6;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "adId")]
        public Guid? AdId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalFaces")]
        public int? TotalFaces { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uniqueFaces")]
        public int? UniqueFaces { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "males")]
        public int? Males { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "females")]
        public int? Females { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket1")]
        public int? AgeBracket1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket2")]
        public int? AgeBracket2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket3")]
        public int? AgeBracket3 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket4")]
        public int? AgeBracket4 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket5")]
        public int? AgeBracket5 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket6")]
        public int? AgeBracket6 { get; set; }

    }
}
