// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ArgonneDashboard.ArgonneServiceClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class AdInCampaignDto
    {
        /// <summary>
        /// Initializes a new instance of the AdInCampaignDto class.
        /// </summary>
        public AdInCampaignDto() { }

        /// <summary>
        /// Initializes a new instance of the AdInCampaignDto class.
        /// </summary>
        public AdInCampaignDto(Guid campaignId, Guid adId, int? sequence = default(int?), int? duration = default(int?), int? firstImpression = default(int?), int? impressionInterval = default(int?))
        {
            CampaignId = campaignId;
            AdId = adId;
            Sequence = sequence;
            Duration = duration;
            FirstImpression = firstImpression;
            ImpressionInterval = impressionInterval;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "campaignId")]
        public Guid CampaignId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "adId")]
        public Guid AdId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sequence")]
        public int? Sequence { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "duration")]
        public int? Duration { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firstImpression")]
        public int? FirstImpression { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "impressionInterval")]
        public int? ImpressionInterval { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
