// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ArgonneDashboard.ArgonneServiceClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Ads
    {
        /// <summary>
        /// Initializes a new instance of the Ads class.
        /// </summary>
        public Ads() { }

        /// <summary>
        /// Initializes a new instance of the Ads class.
        /// </summary>
        public Ads(Guid? adId = default(Guid?), string adName = default(string), string url = default(string), IList<AdsForCampaigns> adsForCampaigns = default(IList<AdsForCampaigns>), IList<Impressions> impressions = default(IList<Impressions>))
        {
            AdId = adId;
            AdName = adName;
            Url = url;
            AdsForCampaigns = adsForCampaigns;
            Impressions = impressions;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "adId")]
        public Guid? AdId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "adName")]
        public string AdName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "adsForCampaigns")]
        public IList<AdsForCampaigns> AdsForCampaigns { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "impressions")]
        public IList<Impressions> Impressions { get; set; }

    }
}
