// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ArgonneDashboard.ArgonneServiceClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class AdsForCampaigns
    {
        /// <summary>
        /// Initializes a new instance of the AdsForCampaigns class.
        /// </summary>
        public AdsForCampaigns() { }

        /// <summary>
        /// Initializes a new instance of the AdsForCampaigns class.
        /// </summary>
        public AdsForCampaigns(Guid? campaignId = default(Guid?), Guid? adId = default(Guid?), int? sequence = default(int?), int? duration = default(int?), int? firstImpression = default(int?), int? impressionInterval = default(int?), Ads ad = default(Ads), Campaigns campaign = default(Campaigns))
        {
            CampaignId = campaignId;
            AdId = adId;
            Sequence = sequence;
            Duration = duration;
            FirstImpression = firstImpression;
            ImpressionInterval = impressionInterval;
            Ad = ad;
            Campaign = campaign;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "campaignId")]
        public Guid? CampaignId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "adId")]
        public Guid? AdId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sequence")]
        public int? Sequence { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "duration")]
        public int? Duration { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firstImpression")]
        public int? FirstImpression { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "impressionInterval")]
        public int? ImpressionInterval { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ad")]
        public Ads Ad { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "campaign")]
        public Campaigns Campaign { get; set; }

    }
}
