// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ArgonneDashboard.ArgonneServiceClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class BiasesForDevices
    {
        /// <summary>
        /// Initializes a new instance of the BiasesForDevices class.
        /// </summary>
        public BiasesForDevices() { }

        /// <summary>
        /// Initializes a new instance of the BiasesForDevices class.
        /// </summary>
        public BiasesForDevices(Guid? deviceId = default(Guid?), string shadowName = default(string), double? countBias = default(double?), double? angerBias = default(double?), double? contemptBias = default(double?), double? disgustBias = default(double?), double? fearBias = default(double?), double? happinessBias = default(double?), double? neutralBias = default(double?), double? sadnessBias = default(double?), double? surpriseBias = default(double?), Devices device = default(Devices))
        {
            DeviceId = deviceId;
            ShadowName = shadowName;
            CountBias = countBias;
            AngerBias = angerBias;
            ContemptBias = contemptBias;
            DisgustBias = disgustBias;
            FearBias = fearBias;
            HappinessBias = happinessBias;
            NeutralBias = neutralBias;
            SadnessBias = sadnessBias;
            SurpriseBias = surpriseBias;
            Device = device;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deviceId")]
        public Guid? DeviceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shadowName")]
        public string ShadowName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "countBias")]
        public double? CountBias { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "angerBias")]
        public double? AngerBias { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contemptBias")]
        public double? ContemptBias { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "disgustBias")]
        public double? DisgustBias { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fearBias")]
        public double? FearBias { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "happinessBias")]
        public double? HappinessBias { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "neutralBias")]
        public double? NeutralBias { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sadnessBias")]
        public double? SadnessBias { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "surpriseBias")]
        public double? SurpriseBias { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "device")]
        public Devices Device { get; set; }

    }
}
