// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ArgonneDashboard.ArgonneServiceClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Campaigns
    {
        /// <summary>
        /// Initializes a new instance of the Campaigns class.
        /// </summary>
        public Campaigns() { }

        /// <summary>
        /// Initializes a new instance of the Campaigns class.
        /// </summary>
        public Campaigns(Guid? campaignId = default(Guid?), string campaignName = default(string), IList<AdsForCampaigns> adsForCampaigns = default(IList<AdsForCampaigns>), IList<Devices> devices = default(IList<Devices>), IList<Impressions> impressions = default(IList<Impressions>))
        {
            CampaignId = campaignId;
            CampaignName = campaignName;
            AdsForCampaigns = adsForCampaigns;
            Devices = devices;
            Impressions = impressions;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "campaignId")]
        public Guid? CampaignId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "campaignName")]
        public string CampaignName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "adsForCampaigns")]
        public IList<AdsForCampaigns> AdsForCampaigns { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "devices")]
        public IList<Devices> Devices { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "impressions")]
        public IList<Impressions> Impressions { get; set; }

    }
}
