// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ArgonneDashboard.ArgonneServiceClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CampaignAdAggregateData
    {

        /// <summary>
        /// Initializes a new instance of the CampaignAdAggregateData class.
        /// </summary>
        public CampaignAdAggregateData() { }

        /// <summary>
        /// Initializes a new instance of the CampaignAdAggregateData class.
        /// </summary>
        public CampaignAdAggregateData(Guid? campaignId = default(Guid?), string campaignName = default(string), Guid? displayedAdId = default(Guid?), string adName = default(string), int? totalFaces = default(int?), int? uniqueFaces = default(int?), string overallSentiment = default(string), double? totalAnger = default(double?), double? totalContempt = default(double?), double? totalDisgust = default(double?), double? totalFear = default(double?), double? totalHappiness = default(double?), double? totalNeutral = default(double?), double? totalSadness = default(double?), double? totalSurprise = default(double?), int? minAge = default(int?), int? maxAge = default(int?), int? uniqueMales = default(int?), int? uniqueFemales = default(int?), int? ageBracket0 = default(int?), int? ageBracket0Males = default(int?), int? ageBracket0Females = default(int?), int? ageBracket1 = default(int?), int? ageBracket1Males = default(int?), int? ageBracket1Females = default(int?), int? ageBracket2 = default(int?), int? ageBracket2Males = default(int?), int? ageBracket2Females = default(int?), int? ageBracket3 = default(int?), int? ageBracket3Males = default(int?), int? ageBracket3Females = default(int?), int? ageBracket4 = default(int?), int? ageBracket4Males = default(int?), int? ageBracket4Females = default(int?), int? ageBracket5 = default(int?), int? ageBracket5Males = default(int?), int? ageBracket5Females = default(int?), int? ageBracket6 = default(int?), int? ageBracket6Males = default(int?), int? ageBracket6Females = default(int?))
        {
            CampaignId = campaignId;
            CampaignName = campaignName;
            DisplayedAdId = displayedAdId;
            AdName = adName;
            TotalFaces = totalFaces;
            UniqueFaces = uniqueFaces;
            OverallSentiment = overallSentiment;
            TotalAnger = totalAnger;
            TotalContempt = totalContempt;
            TotalDisgust = totalDisgust;
            TotalFear = totalFear;
            TotalHappiness = totalHappiness;
            TotalNeutral = totalNeutral;
            TotalSadness = totalSadness;
            TotalSurprise = totalSurprise;
            MinAge = minAge;
            MaxAge = maxAge;
            UniqueMales = uniqueMales;
            UniqueFemales = uniqueFemales;
            AgeBracket0 = ageBracket0;
            AgeBracket0Males = ageBracket0Males;
            AgeBracket0Females = ageBracket0Females;
            AgeBracket1 = ageBracket1;
            AgeBracket1Males = ageBracket1Males;
            AgeBracket1Females = ageBracket1Females;
            AgeBracket2 = ageBracket2;
            AgeBracket2Males = ageBracket2Males;
            AgeBracket2Females = ageBracket2Females;
            AgeBracket3 = ageBracket3;
            AgeBracket3Males = ageBracket3Males;
            AgeBracket3Females = ageBracket3Females;
            AgeBracket4 = ageBracket4;
            AgeBracket4Males = ageBracket4Males;
            AgeBracket4Females = ageBracket4Females;
            AgeBracket5 = ageBracket5;
            AgeBracket5Males = ageBracket5Males;
            AgeBracket5Females = ageBracket5Females;
            AgeBracket6 = ageBracket6;
            AgeBracket6Males = ageBracket6Males;
            AgeBracket6Females = ageBracket6Females;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "campaignId")]
        public Guid? CampaignId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "campaignName")]
        public string CampaignName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "displayedAdId")]
        public Guid? DisplayedAdId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "adName")]
        public string AdName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalFaces")]
        public int? TotalFaces { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uniqueFaces")]
        public int? UniqueFaces { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "overallSentiment")]
        public string OverallSentiment { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalAnger")]
        public double? TotalAnger { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalContempt")]
        public double? TotalContempt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalDisgust")]
        public double? TotalDisgust { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalFear")]
        public double? TotalFear { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalHappiness")]
        public double? TotalHappiness { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalNeutral")]
        public double? TotalNeutral { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalSadness")]
        public double? TotalSadness { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalSurprise")]
        public double? TotalSurprise { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "minAge")]
        public int? MinAge { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maxAge")]
        public int? MaxAge { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uniqueMales")]
        public int? UniqueMales { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uniqueFemales")]
        public int? UniqueFemales { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket0")]
        public int? AgeBracket0 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket0Males")]
        public int? AgeBracket0Males { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket0Females")]
        public int? AgeBracket0Females { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket1")]
        public int? AgeBracket1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket1Males")]
        public int? AgeBracket1Males { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket1Females")]
        public int? AgeBracket1Females { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket2")]
        public int? AgeBracket2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket2Males")]
        public int? AgeBracket2Males { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket2Females")]
        public int? AgeBracket2Females { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket3")]
        public int? AgeBracket3 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket3Males")]
        public int? AgeBracket3Males { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket3Females")]
        public int? AgeBracket3Females { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket4")]
        public int? AgeBracket4 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket4Males")]
        public int? AgeBracket4Males { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket4Females")]
        public int? AgeBracket4Females { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket5")]
        public int? AgeBracket5 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket5Males")]
        public int? AgeBracket5Males { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket5Females")]
        public int? AgeBracket5Females { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket6")]
        public int? AgeBracket6 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket6Males")]
        public int? AgeBracket6Males { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ageBracket6Females")]
        public int? AgeBracket6Females { get; set; }

    }
}
