// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ArgonneDashboard.ArgonneServiceClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Ad Campaign
    /// </summary>
    public partial class CampaignDto
    {
        /// <summary>
        /// Initializes a new instance of the CampaignDto class.
        /// </summary>
        public CampaignDto() { }

        /// <summary>
        /// Initializes a new instance of the CampaignDto class.
        /// </summary>
        public CampaignDto(string campaignName, Guid? campaignId = default(Guid?))
        {
            CampaignId = campaignId;
            CampaignName = campaignName;
        }

        /// <summary>
        /// Globally unique identifier for campaign assigned by Argonne system
        /// </summary>
        [JsonProperty(PropertyName = "campaignId")]
        public Guid? CampaignId { get; set; }

        /// <summary>
        /// Name of Campaign
        /// </summary>
        [JsonProperty(PropertyName = "campaignName")]
        public string CampaignName { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (CampaignName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "CampaignName");
            }
        }
    }
}
