// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ArgonneDashboard.ArgonneServiceClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Devices
    {
        /// <summary>
        /// Initializes a new instance of the Devices class.
        /// </summary>
        public Devices() { }

        /// <summary>
        /// Initializes a new instance of the Devices class.
        /// </summary>
        public Devices(Guid? deviceId = default(Guid?), Guid? assignedCampaignId = default(Guid?), string primaryKey = default(string), string deviceName = default(string), string address = default(string), string address2 = default(string), string address3 = default(string), string city = default(string), string stateProvince = default(string), string postalCode = default(string), DateTime? activeFrom = default(DateTime?), DateTime? activeTo = default(DateTime?), string timezone = default(string), BiasesForDevices biasesForDevices = default(BiasesForDevices), IList<Impressions> impressions = default(IList<Impressions>), Campaigns currentCampaign = default(Campaigns))
        {
            DeviceId = deviceId;
            AssignedCampaignId = assignedCampaignId;
            PrimaryKey = primaryKey;
            DeviceName = deviceName;
            Address = address;
            Address2 = address2;
            Address3 = address3;
            City = city;
            StateProvince = stateProvince;
            PostalCode = postalCode;
            ActiveFrom = activeFrom;
            ActiveTo = activeTo;
            Timezone = timezone;
            BiasesForDevices = biasesForDevices;
            Impressions = impressions;
            CurrentCampaign = currentCampaign;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deviceId")]
        public Guid? DeviceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assignedCampaignId")]
        public Guid? AssignedCampaignId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "primaryKey")]
        public string PrimaryKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deviceName")]
        public string DeviceName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public string Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address2")]
        public string Address2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address3")]
        public string Address3 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "city")]
        public string City { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stateProvince")]
        public string StateProvince { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "postalCode")]
        public string PostalCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "activeFrom")]
        public DateTime? ActiveFrom { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "activeTo")]
        public DateTime? ActiveTo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timezone")]
        public string Timezone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "biasesForDevices")]
        public BiasesForDevices BiasesForDevices { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "impressions")]
        public IList<Impressions> Impressions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currentCampaign")]
        public Campaigns CurrentCampaign { get; set; }

    }
}
